export type ArticleSection = {
  type: 'h2' | 'h3' | 'p' | 'ul' | 'cta'
  text?: string
  items?: string[]
}

export type ArticleData = {
  slug: string
  date: string
  readTime: number
  keywords: string[]
  metaDesc: string
  sections: ArticleSection[]
}

export type LocaleArticles = {
  ar: ArticleData
  en: ArticleData
}

export const articles: Record<string, LocaleArticles> = {
  'marriage-contract-requirements-non-jordanians': {
    ar: {
      slug: 'marriage-contract-requirements-non-jordanians',
      date: '2026-04-15',
      readTime: 10,
      keywords: [
        'زواج الأجانب في الأردن',
        'شروط الزواج لغير الأردنيين',
        'إجراءات عقد الزواج الشرعي',
        'محامي زواج الأجانب',
        'توثيق عقد الزواج الأردن',
      ],
      metaDesc: 'دليل قانوني شامل لشروط وإجراءات عقد الزواج لغير الأردنيين في الأردن، الوثائق المطلوبة، خطوات التسجيل، والتحديات الشائعة مع حلولها القانونية.',
      sections: [
        { type: 'h2', text: 'مقدمة عن زواج الأجانب في الأردن' },
        { type: 'p', text: 'يستقطب الأردن أعداداً كبيرة من الأجانب والمغتربين والمقيمين الراغبين في إتمام عقود زواجهم وفق الأحكام الشرعية والقانون الأردني. وقد يجد كثيرون منهم أنفسهم في مواجهة منظومة إجرائية معقدة تتطلب معرفة دقيقة بالقوانين المحلية والدولية. من هنا تبرز أهمية الاستعانة بمحامٍ شرعي متخصص لضمان صحة العقد وسريانه القانوني.' },
        { type: 'p', text: 'يختص مكتب المحامي الشرعي أحمد الجراح بتقديم خدمات توثيق عقود الزواج للأجانب والمغتربين والمقيمين في الأردن، مع الإشراف الكامل على كل مراحل الإجراءات من الاستشارة الأولى حتى الحصول على وثيقة الزواج الرسمية.' },
        { type: 'h2', text: 'الشروط القانونية لعقد الزواج' },
        { type: 'p', text: 'يشترط القانون الأردني لصحة عقد الزواج جملةً من الشروط الجوهرية، أبرزها: الأهلية القانونية (بلوغ سن الرشد وعدم الحجر)، والرضا الصريح من الطرفين، وحضور الولي الشرعي بالنسبة للمرأة، وشهادة شاهدَين مسلمَين بالغَين عاقلَين، فضلاً عن الخلو من موانع الزواج الشرعية كالمحارم والعدة.' },
        { type: 'p', text: 'أما بالنسبة لغير الأردنيين فيُضاف إلى ذلك اشتراطات إضافية تتعلق بالوضع القانوني للإقامة، والجنسية، وأحياناً الديانة، وفق ضوابط الشريعة الإسلامية المعمول بها في المحاكم الشرعية الأردنية.' },
        { type: 'h2', text: 'الوثائق المطلوبة' },
        { type: 'h3', text: 'للزوج' },
        {
          type: 'ul',
          items: [
            'جواز السفر ساري المفعول أو إثبات هوية رسمي',
            'وثيقة إقامة قانونية في الأردن (إن وُجدت)',
            'شهادة عدم الزواج أو وثيقة الطلاق (إن انطبق)',
            'تصريح من سفارة بلده يفيد بأهليته للزواج (للأجانب)',
            'صورة عن الهوية مصدّقة',
          ],
        },
        { type: 'h3', text: 'للزوجة' },
        {
          type: 'ul',
          items: [
            'جواز السفر ساري المفعول أو إثبات هوية رسمي',
            'وثيقة إقامة قانونية',
            'شهادة عدم الزواج أو وثيقة الطلاق',
            'موافقة الولي الشرعي ووثيقة إثبات صلة القرابة',
            'في حالة الأرملة: وثيقة وفاة الزوج السابق',
          ],
        },
        { type: 'h2', text: 'خطوات تسجيل عقد الزواج في المحكمة الشرعية' },
        {
          type: 'ul',
          items: [
            'تقديم طلب الزواج إلى المحكمة الشرعية المختصة',
            'التحقق من استيفاء الوثائق المطلوبة من الطرفين',
            'إجراء جلسة العقد بحضور الطرفين والولي والشهود',
            'توقيع عقد الزواج الرسمي وتوثيقه لدى القاضي الشرعي',
            'استخراج وثيقة الزواج الرسمية من ديوان المحكمة',
            'إجراءات التصديق والتوثيق الرسمي إن لزم',
          ],
        },
        { type: 'h2', text: 'الحالات الخاصة' },
        { type: 'p', text: 'تختلف إجراءات الزواج بحسب جنسية الطرفين وديانتهما. فبالنسبة لزواج المسلم من غير المسلمة تُطبَّق قواعد خاصة تعتمد على مذهب الزوج وجنسيته. أما زواج غير المسلمين فيجري وفق الأنظمة الدينية المعترف بها في المملكة. وفي حالات اختلاف الديانة بين الطرفين، قد تكون المحكمة الشرعية هي الجهة المختصة أو قد يُحال الأمر إلى القضاء المدني.' },
        { type: 'h2', text: 'الإجراءات بعد توثيق العقد' },
        {
          type: 'ul',
          items: [
            'تسجيل عقد الزواج في سجلات الأحوال المدنية',
            'التصديق على الوثيقة من وزارة الخارجية والتوثيق الدبلوماسي',
            'الاعتراف بالزواج في دولة الزوج أو الزوجة الأجنبي',
            'تحديث وثائق الإقامة والجنسية إن لزم',
          ],
        },
        { type: 'h2', text: 'التحديات الشائعة والحلول القانونية' },
        { type: 'p', text: 'تبرز عدة تحديات عملية في زواج الأجانب، منها: صعوبة الحصول على تصريح الزواج من سفارات بعض الدول، أو الاختلاف في المتطلبات بين الجنسيات المختلفة، أو عقبات اللغة في فهم الإجراءات. كذلك قد تكون وثائق بعض الدول غير مألوفة للجهات الأردنية. يتمثل الحل في الاستعانة بمحامٍ متخصص يُنسّق مع الجهات الرسمية ويُعدّ الملف القانوني بصورة كاملة.' },
        { type: 'h2', text: 'لماذا تحتاج محامياً متخصصاً؟' },
        { type: 'p', text: 'يُعدّ الاستعانة بمحامٍ شرعي متخصص في زواج الأجانب خطوةً ضرورية لا اختيارية. فالأخطاء الإجرائية قد تُفضي إلى بطلان العقد أو تأخيره لأشهر، بل قد تُعرّض الطرفين لإشكاليات قانونية خطيرة. المحامي المتخصص يضمن صحة كل خطوة، ويُخلّص المعاملة بأسرع وقت وأقل تعقيد.' },
        { type: 'h2', text: 'كيف نساعدك في مكتب المحامي أحمد الجراح؟' },
        {
          type: 'ul',
          items: [
            'استشارة قانونية شاملة لتقييم وضعك الخاص',
            'إعداد وتنظيم كامل ملف الوثائق المطلوبة',
            'التنسيق مع المحكمة الشرعية المختصة وتحديد مواعيد الجلسات',
            'متابعة جميع مراحل الإجراءات نيابةً عنك',
            'إمكانية التوثيق بالوكالة دون الحضور الشخصي للطرفين في حالات معينة',
            'خدمة إلكترونية متكاملة وسرية تامة',
          ],
        },
        { type: 'cta', text: 'احجز استشارتك مع المحامي أحمد الجراح اليوم' },
      ],
    },
    en: {
      slug: 'marriage-contract-requirements-non-jordanians',
      date: '2026-04-15',
      readTime: 10,
      keywords: [
        'marriage of foreigners in Jordan',
        'non-Jordanian marriage requirements',
        'foreign marriage procedures Jordan',
        'sharia marriage contract Jordan',
        'expat marriage Jordan lawyer',
      ],
      metaDesc: 'Complete legal guide to marriage contract requirements and procedures for non-Jordanians in Jordan — required documents, court steps, special cases, and common challenges solved.',
      sections: [
        { type: 'h2', text: 'Introduction: Marriage for Foreigners in Jordan' },
        { type: 'p', text: 'Jordan attracts a large number of foreigners, expatriates, and residents who wish to formalize their marriage under Islamic Sharia law and Jordanian legal frameworks. Many find themselves navigating a complex procedural system that demands precise knowledge of both local and international regulations. This is where a specialized Sharia lawyer becomes indispensable.' },
        { type: 'p', text: 'Ahmad Aljarrah Law Firm specializes in marriage contract documentation for foreigners, expats, and residents in Jordan, providing full oversight of every procedural stage from the initial consultation through to obtaining the official marriage certificate.' },
        { type: 'h2', text: 'Legal Requirements for a Marriage Contract' },
        { type: 'p', text: 'Jordanian law requires several fundamental conditions for a valid marriage contract: legal capacity (reaching adulthood and not being under guardianship), explicit consent from both parties, presence of the woman\'s legal guardian (wali), testimony of two adult Muslim witnesses of sound mind, and the absence of Sharia prohibitions such as close relatives and waiting periods (iddah).' },
        { type: 'p', text: 'For non-Jordanians, additional requirements apply related to residency status, nationality, and sometimes religion, in accordance with Islamic Sharia principles as applied in Jordanian Sharia courts.' },
        { type: 'h2', text: 'Required Documents' },
        { type: 'h3', text: 'For the Groom' },
        {
          type: 'ul',
          items: [
            'Valid passport or official government-issued ID',
            'Legal residency document in Jordan (if applicable)',
            'Certificate of bachelorhood or divorce certificate (if applicable)',
            'Authorization from the embassy of the groom\'s country confirming eligibility to marry (for foreigners)',
            'Certified copy of ID',
          ],
        },
        { type: 'h3', text: 'For the Bride' },
        {
          type: 'ul',
          items: [
            'Valid passport or official government-issued ID',
            'Legal residency document',
            'Certificate of bachelorhood or divorce certificate',
            'Legal guardian\'s consent and proof of kinship',
            'In case of a widow: death certificate of the previous husband',
          ],
        },
        { type: 'h2', text: 'Steps to Register a Marriage in Sharia Court' },
        {
          type: 'ul',
          items: [
            'Submit marriage application to the competent Sharia Court',
            'Verify that all required documents from both parties are complete',
            'Conduct the contract session with both parties, the guardian, and witnesses present',
            'Sign and authenticate the official marriage contract before the Sharia judge',
            'Obtain the official marriage certificate from the court registry',
            'Proceed with official attestation and notarization if required',
          ],
        },
        { type: 'h2', text: 'Special Cases' },
        { type: 'p', text: 'Marriage procedures vary based on the nationality and religion of both parties. For a Muslim man marrying a non-Muslim woman, specific rules apply based on the husband\'s school of law and nationality. Marriage between non-Muslims follows rules of recognized religious communities in the Kingdom. In cases of religious differences between the parties, the Sharia court may have jurisdiction or the matter may be referred to civil courts.' },
        { type: 'h2', text: 'Post-Contract Procedures' },
        {
          type: 'ul',
          items: [
            'Registering the marriage contract in civil status records',
            'Attesting the document at the Ministry of Foreign Affairs and diplomatic authentication',
            'Recognition of the marriage in the foreign spouse\'s country of origin',
            'Updating residency and citizenship documents as needed',
          ],
        },
        { type: 'h2', text: 'Common Challenges and Legal Solutions' },
        { type: 'p', text: 'Several practical challenges arise in foreign marriages: difficulty obtaining marriage authorization from some embassies, differences in requirements across nationalities, language barriers in understanding procedures, or documents from certain countries being unfamiliar to Jordanian authorities. The solution lies in engaging a specialist lawyer who coordinates with official authorities and prepares a complete legal file.' },
        { type: 'h2', text: 'Why Do You Need a Specialized Lawyer?' },
        { type: 'p', text: 'Engaging a Sharia lawyer specializing in foreign marriages is a necessary, not optional, step. Procedural errors can lead to contract invalidation, months of delays, or serious legal complications for both parties. A specialist lawyer guarantees the validity of every step and expedites the process with minimal complications.' },
        { type: 'h2', text: 'How We Help at Ahmad Aljarrah Law Firm' },
        {
          type: 'ul',
          items: [
            'Comprehensive legal consultation to assess your specific situation',
            'Full preparation and organization of the required documents file',
            'Coordination with the competent Sharia Court and scheduling sessions',
            'Following up on all procedural stages on your behalf',
            'Possibility of documentation by proxy without personal attendance in certain cases',
            'Complete online service with full confidentiality',
          ],
        },
        { type: 'cta', text: 'Book Your Consultation with Ahmad Aljarrah Today' },
      ],
    },
  },
  'foreign-marriage-divorce-procedures-jordan': {
    ar: {
      slug: 'foreign-marriage-divorce-procedures-jordan',
      date: '2026-03-20',
      readTime: 12,
      keywords: [
        'طلاق الأجانب في الأردن',
        'زواج المغتربين',
        'محامي شرعي عمان',
        'محامي شرعي إربد',
        'إجراءات الطلاق في الأردن',
      ],
      metaDesc: 'دليل متكامل لإجراءات زواج وطلاق الأجانب والمغتربين والمقيمين في الأردن — الإطار القانوني، الفرق بين الطلاق والخلع، حقوق الأطفال، وتنفيذ الأحكام الأجنبية.',
      sections: [
        { type: 'h2', text: 'مقدمة: الزواج والطلاق للأجانب في الأردن' },
        { type: 'p', text: 'يُعدّ الأردن وجهةً مفضّلة للكثير من الأجانب والمغتربين العرب والأجانب، سواء للإقامة أو العمل أو الدراسة. وفي خضمّ هذا الواقع، يواجه كثيرون منهم تحديات قانونية تتعلق بالزواج أو الطلاق في ظل بيئة قانونية مختلفة عن بلدانهم الأصلية. يُعالج هذا المقال الإطار القانوني الأردني وأهم الإجراءات العملية للأجانب والمغتربين.' },
        { type: 'h2', text: 'الإطار القانوني الأردني للأجانب والمقيمين' },
        { type: 'p', text: 'يستند القضاء الشرعي في الأردن إلى أحكام الشريعة الإسلامية والقانون رقم 36 لسنة 2010 (قانون الأحوال الشخصية) وتعديلاته. تختص المحاكم الشرعية بالنظر في قضايا الزواج والطلاق والحضانة والنفقة والإرث للمسلمين، وفق ولاية قضائية تمتد لتشمل المقيمين الأجانب.' },
        { type: 'p', text: 'يحق للأجنبي المقيم في الأردن اللجوء إلى المحاكم الشرعية لإتمام زواجه أو طلاقه، مع مراعاة خصوصية القانون الدولي الخاص فيما يتعلق بتنازع القوانين.' },
        { type: 'h2', text: 'إجراءات الزواج خطوة بخطوة' },
        {
          type: 'ul',
          items: [
            'الحصول على الوثائق المطلوبة (جوازات السفر، شهادات الحالة المدنية)',
            'التصديق على الوثائق الأجنبية بالأبوستيل أو عبر السفارة',
            'تقديم الطلب إلى المحكمة الشرعية المختصة',
            'استيفاء شرط الولي والشهود',
            'إبرام العقد أمام القاضي الشرعي',
            'استخراج وثيقة الزواج وتوثيقها رسمياً',
          ],
        },
        { type: 'h2', text: 'إجراءات الطلاق للأجانب' },
        { type: 'p', text: 'يحق للزوج الأجنبي المقيم في الأردن طلب الطلاق أمام المحكمة الشرعية. تبدأ الإجراءات بتقديم الطلب وإشعار الطرف الآخر، تليها جلسات الاستماع والمحاولة للإصلاح، وصولاً إلى إصدار حكم الطلاق. وتختلف الإجراءات بحسب نوع الطلاق (شقاق، خلع، إبراء).' },
        { type: 'h2', text: 'الفرق بين الطلاق والخلع والفسخ' },
        {
          type: 'ul',
          items: [
            'الطلاق: يصدر من الزوج ويحتفظ بحقه الشرعي في الرجعة خلال العدة',
            'الخلع: تطلبه الزوجة مقابل ردّ المهر أو جزء منه، وهو طلاق بائن',
            'الفسخ: يصدر عن المحكمة بسبب ضرر أو غيبة أو عجز أو ردّة',
            'الشقاق: دعوى ترفعها الزوجة لعدم الانسجام وتعيّن المحكمة حكمَين للإصلاح',
          ],
        },
        { type: 'h2', text: 'حقوق الأطفال في حالات الطلاق الدولية' },
        { type: 'p', text: 'حين يكون أحد الوالدين أجنبياً، تنشأ تعقيدات إضافية تخص الحضانة والزيارة وإذن السفر بالأطفال عبر الحدود. يكفل القانون الأردني مصلحة الطفل الفضلى، ويمنح الأم الأولوية في الحضانة حتى سن الخامسة عشرة، مع حق الأب في المشاهدة المنتظمة. وفي القضايا الدولية، قد تُطلب ضمانات بعدم المغادرة أو إذن قضائي للسفر.' },
        { type: 'h2', text: 'تنفيذ الأحكام الأجنبية في الأردن' },
        { type: 'p', text: 'تخضع الأحكام الأجنبية الصادرة في دعاوى الزواج والطلاق لإجراء الإكساء بالصيغة التنفيذية في الأردن، بشرط المعاملة بالمثل وعدم مخالفة النظام العام. يختص بذلك القضاء الأردني بعد التحقق من شروط الاعتراف الدولية.' },
        { type: 'h2', text: 'الفرق بين الزواج المدني والزواج الشرعي' },
        { type: 'p', text: 'لا يعترف القانون الأردني بالزواج المدني وحده أمام المحاكم الشرعية في الغالب. والزواج المعقود في الخارج عقداً مدنياً يحتاج إلى إثبات خاص وقد يتطلب توثيقاً شرعياً إضافياً لضمان تطبيق أحكامه أردنياً.' },
        { type: 'h2', text: 'الأخطاء الشائعة وكيفية تجنبها' },
        {
          type: 'ul',
          items: [
            'إغفال الحصول على موافقة السفارة قبل الزواج',
            'إهمال توثيق الوثائق الأجنبية بصورة رسمية',
            'الخلط بين الاختصاص القضائي الأردني والأجنبي',
            'عدم تسجيل حكم الطلاق في دولة الزوج الأجنبي',
            'تأخير إجراءات ترتيب الحضانة بعد الطلاق الدولي',
          ],
        },
        { type: 'h2', text: 'خدماتنا في عمان وإربد والزرقاء' },
        { type: 'p', text: 'يقدم مكتب المحامي أحمد الجراح خدماته القانونية الشرعية في جميع أنحاء الأردن، مع تركيز خاص على محاكم إربد وعمان والزرقاء. نتولى ملف الأجانب والمغتربين بعناية فائقة، ونضمن إتمام إجراءات الزواج والطلاق بصورة شرعية وقانونية سليمة.' },
        { type: 'cta', text: 'تواصل معنا الآن للحصول على استشارتك' },
      ],
    },
    en: {
      slug: 'foreign-marriage-divorce-procedures-jordan',
      date: '2026-03-20',
      readTime: 12,
      keywords: [
        'foreign divorce Jordan',
        'expat divorce Jordan',
        'family law Jordan',
        'sharia lawyer Amman',
        'sharia lawyer Irbid',
      ],
      metaDesc: 'Complete guide to marriage and divorce procedures for foreigners, expats, and residents in Jordan — legal framework, types of divorce, children\'s rights, and foreign judgment enforcement.',
      sections: [
        { type: 'h2', text: 'Introduction: Marriage and Divorce for Foreigners in Jordan' },
        { type: 'p', text: 'Jordan is a preferred destination for many Arab and foreign expatriates, whether for residence, work, or study. In this context, many face legal challenges related to marriage or divorce within a legal environment different from their home countries. This article addresses the Jordanian legal framework and key practical procedures for foreigners and expatriates.' },
        { type: 'h2', text: 'Jordanian Legal Framework for Foreigners and Residents' },
        { type: 'p', text: 'Jordanian Sharia courts operate under Islamic Sharia principles and Law No. 36 of 2010 (Personal Status Law) and its amendments. Sharia courts have jurisdiction over marriage, divorce, custody, alimony, and inheritance cases for Muslims, with jurisdiction extending to cover foreign residents.' },
        { type: 'p', text: 'A foreign resident in Jordan has the right to approach Sharia courts to complete marriage or divorce procedures, while considering the specifics of private international law regarding conflicts of laws.' },
        { type: 'h2', text: 'Step-by-Step Marriage Procedures' },
        {
          type: 'ul',
          items: [
            'Obtain required documents (passports, civil status certificates)',
            'Authenticate foreign documents via Apostille or through the embassy',
            'Submit application to the competent Sharia Court',
            'Fulfill the guardian (wali) and witness requirements',
            'Execute the contract before the Sharia judge',
            'Obtain and officially notarize the marriage certificate',
          ],
        },
        { type: 'h2', text: 'Divorce Procedures for Foreigners' },
        { type: 'p', text: 'A foreign resident in Jordan can request divorce before the Sharia Court. Proceedings begin with filing the application and notifying the other party, followed by hearing sessions with reconciliation attempts, leading to the issuance of a divorce judgment. Procedures differ based on divorce type (marital discord, khula, no-fault divorce).' },
        { type: 'h2', text: 'Difference Between Divorce, Khul\', and Annulment' },
        {
          type: 'ul',
          items: [
            'Divorce (Talaq): initiated by the husband, with right of revocation during the iddah period',
            'Khul\': requested by the wife in exchange for returning the dowry or part of it — irrevocable',
            'Annulment (Faskh): issued by the court due to harm, absence, inability, or apostasy',
            'Marital Discord (Shiqaq): lawsuit filed by the wife; the court appoints two arbitrators for reconciliation',
          ],
        },
        { type: 'h2', text: 'Children\'s Rights in International Divorce Cases' },
        { type: 'p', text: 'When one parent is a foreigner, additional complexities arise regarding custody, visitation, and travel permission for children across borders. Jordanian law guarantees the child\'s best interests, giving the mother priority in custody until age 15, with the father having regular visitation rights. In international cases, no-travel guarantees or court permission for travel may be required.' },
        { type: 'h2', text: 'Foreign Judgment Enforcement in Jordan' },
        { type: 'p', text: 'Foreign judgments issued in marriage and divorce cases are subject to the enforcement exequatur procedure in Jordan, provided there is reciprocity and the judgment does not violate public order. Jordanian courts handle this after verifying international recognition conditions.' },
        { type: 'h2', text: 'Difference Between Civil and Sharia Marriage' },
        { type: 'p', text: 'Jordanian law generally does not recognize civil marriage alone before Sharia courts. A marriage contracted abroad as a civil union may require special proof and possibly additional Sharia documentation to ensure its provisions apply in Jordan.' },
        { type: 'h2', text: 'Common Mistakes and How to Avoid Them' },
        {
          type: 'ul',
          items: [
            'Overlooking the requirement for embassy approval before marriage',
            'Neglecting to officially authenticate foreign documents',
            'Confusing Jordanian and foreign judicial jurisdiction',
            'Failing to register a divorce judgment in the foreign spouse\'s country',
            'Delaying custody arrangements after an international divorce',
          ],
        },
        { type: 'h2', text: 'Our Services in Amman, Irbid, and Zarqa' },
        { type: 'p', text: 'Ahmad Aljarrah Law Firm provides Sharia legal services across Jordan, with special focus on courts in Irbid, Amman, and Zarqa. We handle foreign and expat cases with meticulous care, ensuring marriage and divorce procedures are completed in a fully lawful and Sharia-compliant manner.' },
        { type: 'cta', text: 'Contact Us Now for Your Consultation' },
      ],
    },
  },
  'arbitrary-divorce-compensation-jordan': {
    ar: {
      slug: 'arbitrary-divorce-compensation-jordan',
      date: '2026-02-28',
      readTime: 11,
      keywords: [
        'الطلاق التعسفي في الأردن',
        'تعويض الطلاق',
        'حقوق المرأة المطلقة',
        'نفقة العدة',
        'المطالبة بالتعويض بعد الطلاق',
      ],
      metaDesc: 'دليل قانوني شامل حول التعويض عن الطلاق التعسفي في الأردن — شروط الاستحقاق، كيفية التقدير، الأدلة المطلوبة، وإجراءات المطالبة القضائية.',
      sections: [
        { type: 'h2', text: 'تعريف الطلاق التعسفي في القانون الأردني' },
        { type: 'p', text: 'يُعرَّف الطلاق التعسفي في قانون الأحوال الشخصية الأردني رقم 36 لسنة 2010 بأنه الطلاق الذي يقع من الزوج دون مسوّغ مقبول، ويُلحق ضرراً بالغاً بالزوجة. وقد منح المشرّع الأردني الزوجة المطلقة تعسفياً الحقَّ في المطالبة بتعويض مناسب، تقديراً للضرر المادي والمعنوي الذي لحق بها.' },
        { type: 'p', text: 'يستهدف نظام التعويض هذا تحقيق التوازن في العلاقة الزوجية، ومنع إساءة استخدام حق الطلاق الذي يملكه الزوج من الناحية الشرعية، مع صون كرامة الزوجة وضمان حقوقها الأساسية.' },
        { type: 'h2', text: 'شروط استحقاق التعويض' },
        {
          type: 'ul',
          items: [
            'أن يكون الطلاق بدون سبب مقبول شرعاً وقانوناً',
            'أن يثبت أن الزوجة ليست ناشزاً أو مُقصِّرة في واجباتها الزوجية',
            'أن يكون الطلاق قد أوقع ضرراً مادياً أو معنوياً ملموساً',
            'أن يُقدَّم الطلب في المهلة القانونية المحددة',
          ],
        },
        { type: 'h2', text: 'كيف يتم تقدير التعويض؟' },
        { type: 'p', text: 'لا يوجد مبلغ محدد مسبقاً للتعويض في القانون الأردني. يقدّره القاضي بحسب السلطة التقديرية مراعياً جملة من العوامل: مدة الزواج، مستوى معيشة الزوجة السابق، وجود أطفال، عمر الزوجة وفرص إعادة زواجها، ومدى الضرر الفعلي الذي لحق بها.' },
        { type: 'h2', text: 'الفرق بين نفقة العدة والتعويض' },
        {
          type: 'ul',
          items: [
            'نفقة العدة: واجبة شرعاً للمرأة المطلقة رجعياً أو بائناً، تمتد لثلاثة أشهر أو حتى الوضع',
            'المتعة: هدية شرعية يُلزم بها الزوج المطلِّق قبل الدخول أو تعسفاً',
            'التعويض: مبلغ إضافي يُقضى به من قِبل المحكمة جبراً للضرر الخاص بالطلاق التعسفي',
          ],
        },
        { type: 'h2', text: 'حقوق الزوجة المالية بعد الطلاق التعسفي' },
        { type: 'p', text: 'تملك الزوجة المطلقة تعسفياً حزمة من الحقوق المالية التي تتضمن: المهر المؤجل كاملاً، نفقة العدة، المتعة الشرعية، التعويض القضائي عن الضرر، نفقة الأطفال وأجور الحضانة، وبدل المسكن. وتُرفع هذه المطالبات عادةً في دعوى واحدة أو دعاوى متعددة أمام المحكمة الشرعية.' },
        { type: 'h2', text: 'الأدلة المطلوبة لإثبات الضرر' },
        {
          type: 'ul',
          items: [
            'وثيقة الزواج وما تتضمنه من شروط',
            'وثيقة الطلاق ونص حجة الطلاق',
            'شهادة الشهود على الطلاق ومحيطه',
            'أي وثائق تُثبت الضرر المادي أو المعنوي (رسائل، وثائق مالية)',
            'تقارير اجتماعية أو نفسية إن توفرت',
          ],
        },
        { type: 'h2', text: 'مدة الدعوى والإجراءات القضائية' },
        { type: 'p', text: 'تتراوح مدة البت في دعاوى تعويض الطلاق التعسفي في الأردن بين ثلاثة أشهر وسنة، وفق تعقيد القضية وجدول أعمال المحكمة. تبدأ بتقديم اللائحة، ثم الإشعار والتبليغ، فجلسات الاستماع، وصولاً إلى الحكم الابتدائي والاستئناف إن لزم.' },
        { type: 'h2', text: 'أمثلة من القضايا الناجحة' },
        { type: 'p', text: 'رافق مكتب المحامي أحمد الجراح عدداً من الزوجات اللواتي تعرّضن للطلاق التعسفي بعد زيجات طويلة، وتمكّن من انتزاع تعويضات مجزية لهن تراوحت بين ستة أشهر وسنتين من دخل الزوج، إلى جانب كامل المستحقات المالية الأخرى.' },
        { type: 'h2', text: 'نصائح للمرأة المطلقة' },
        {
          type: 'ul',
          items: [
            'احتفظي بنسخة من عقد الزواج وكافة الوثائق المتعلقة به',
            'لا تتنازلي عن حقوقك تحت الضغط العاطفي',
            'تواصلي مع محامٍ متخصص فور وقوع الطلاق وقبل انتهاء مدة العدة',
            'وثّقي أي أدلة على الضرر المادي أو المعنوي',
            'لا تقبلي تسويات ودية قبل الاستشارة القانونية',
          ],
        },
        { type: 'h2', text: 'كيف نساعدك في الحصول على حقوقك؟' },
        { type: 'p', text: 'يقدم مكتب المحامي أحمد الجراح خدمة قانونية متكاملة للمرأة المطلقة تشمل تقييم قضيتها، إعداد لائحة الدعوى، جمع الأدلة، والمرافعة أمام المحاكم الشرعية. نضمن لك الحصول على كامل حقوقك القانونية بسرية تامة وكفاءة عالية.' },
        { type: 'cta', text: 'احجز استشارتك الآن للدفاع عن حقوقك' },
      ],
    },
    en: {
      slug: 'arbitrary-divorce-compensation-jordan',
      date: '2026-02-28',
      readTime: 11,
      keywords: [
        'arbitrary divorce Jordan',
        'divorce compensation Jordan',
        'women rights divorce Jordan',
        'iddah alimony Jordan',
        'divorce damage claim Jordan',
      ],
      metaDesc: 'Comprehensive legal guide on arbitrary divorce compensation in Jordan — eligibility conditions, assessment method, required evidence, and judicial procedures for claiming rights.',
      sections: [
        { type: 'h2', text: 'Definition of Arbitrary Divorce in Jordanian Law' },
        { type: 'p', text: 'Arbitrary divorce is defined in Jordan\'s Personal Status Law No. 36 of 2010 as a divorce initiated by the husband without acceptable justification, causing significant harm to the wife. The Jordanian legislature has granted the arbitrarily divorced wife the right to claim appropriate compensation in recognition of the material and moral damage she has suffered.' },
        { type: 'p', text: 'This compensation system aims to balance the marital relationship, prevent abuse of the husband\'s Sharia right to divorce, while preserving the wife\'s dignity and securing her fundamental rights.' },
        { type: 'h2', text: 'Conditions for Compensation Eligibility' },
        {
          type: 'ul',
          items: [
            'The divorce must have occurred without Sharia or legal justification',
            'The wife must not be in a state of disobedience (nushuz) or neglect of marital duties',
            'The divorce must have caused tangible material or moral harm',
            'The claim must be filed within the legally specified timeframe',
          ],
        },
        { type: 'h2', text: 'How Is the Compensation Assessed?' },
        { type: 'p', text: 'There is no predetermined compensation amount in Jordanian law. The judge estimates it at discretionary judgment, considering several factors: duration of marriage, the wife\'s previous standard of living, presence of children, the wife\'s age and remarriage prospects, and the extent of actual harm suffered.' },
        { type: 'h2', text: 'Difference Between Iddah Alimony and Compensation' },
        {
          type: 'ul',
          items: [
            'Iddah Alimony: obligatory under Sharia for the revocably or irrevocably divorced woman, lasting three months or until childbirth',
            'Muta\'a (Gift): a Sharia-mandated gift the divorcing husband must provide if divorce occurred before consummation or arbitrarily',
            'Compensation: an additional amount ordered by the court to redress the specific harm of arbitrary divorce',
          ],
        },
        { type: 'h2', text: 'Wife\'s Financial Rights After Arbitrary Divorce' },
        { type: 'p', text: 'The arbitrarily divorced wife has a package of financial rights including: full deferred dowry, iddah alimony, Muta\'a (gift), judicial compensation for damages, child alimony and custody fees, and housing allowance. These claims are typically filed in one or multiple lawsuits before the Sharia Court.' },
        { type: 'h2', text: 'Evidence Required to Prove Harm' },
        {
          type: 'ul',
          items: [
            'The marriage contract and any special conditions therein',
            'The divorce certificate and the divorce document text',
            'Witness testimony about the divorce and its circumstances',
            'Any documents proving material or moral harm (messages, financial documents)',
            'Social or psychological reports if available',
          ],
        },
        { type: 'h2', text: 'Case Duration and Judicial Procedures' },
        { type: 'p', text: 'Arbitrary divorce compensation cases in Jordan typically take between three months and one year, depending on the case complexity and court calendar. The process begins with filing the claim, then notification, hearing sessions, leading to the initial judgment and appeal if necessary.' },
        { type: 'h2', text: 'Examples from Successful Cases' },
        { type: 'p', text: 'Ahmad Aljarrah Law Firm has represented numerous wives who suffered arbitrary divorce after long marriages, successfully securing substantial compensation ranging from six months to two years of the husband\'s income, along with all other financial entitlements.' },
        { type: 'h2', text: 'Advice for the Divorced Woman' },
        {
          type: 'ul',
          items: [
            'Keep a copy of the marriage contract and all related documents',
            'Do not relinquish your rights under emotional pressure',
            'Contact a specialist lawyer immediately after the divorce and before the iddah period ends',
            'Document any evidence of material or moral harm',
            'Do not accept amicable settlements before obtaining legal consultation',
          ],
        },
        { type: 'h2', text: 'How We Help You Obtain Your Rights' },
        { type: 'p', text: 'Ahmad Aljarrah Law Firm provides a comprehensive legal service for divorced women, including case assessment, claim preparation, evidence collection, and litigation before Sharia courts. We guarantee you obtain all your legal rights with complete confidentiality and high efficiency.' },
        { type: 'cta', text: 'Book Your Consultation Now to Defend Your Rights' },
      ],
    },
  },
}
